apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp-frontend
  labels:
    name: miapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miapp-frontend
  template:
    metadata:
      labels:
        app: miapp-frontend
    spec:
      containers:
        - name: miapp-frontend
          image: mnroman/miapp-frontend:v1
          imagePullPolicy: Always
          env:
            - name: COUNTER_ENDPOINT
              value: "http://miapp-backend.default.svc.cluster.local:5000"
          ports:
            - name: frontend-port
              containerPort: 8000
              protocol: TCP
